### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by mvollmer** [mvollmer/magit#1]
Just for testing.

**Comment by tarsius** [comment]
What are your plans?

**Comment by mvollmer** [comment]
Upps, shouldn't have used the magit repo for this...  I wanted to see how one can export issues from Github.  Maybe you thought this was about adding tests to magit?  Sorry for the confusion.

**Comment by randomwangran** [comment]
Just happen to see this funny 404...

https://magit.vc/manual/magit/Getting-Started#Getting-Started

want to do a thumb up for you!
